stages:
  - release

variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  APP_ENV: prod
  SYMFONY_ENV: prod
  COMPOSER_ALLOW_SUPERUSER: "1"


semantic_release:
  stage: release
  image: node:22
  resource_group: semantic_release_group
  interruptible: true
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"
    - git fetch --all --tags --prune
    # CRITICAL: Reset local dev branch to match remote
    - git checkout $CI_COMMIT_BRANCH
    - git reset --hard origin/$CI_COMMIT_BRANCH
  script:
    - npm ci
    - npx semantic-release --debug --no-ci